/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects.index'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ErrorKindRouteImport } from './routes/error.$kind'
import { Route as AuthenticatedSalesWorkflowRouteImport } from './routes/_authenticated/sales-workflow'
import { Route as AuthenticatedMemberRouteImport } from './routes/_authenticated/member'
import { Route as AuthenticatedLeaderRouteImport } from './routes/_authenticated/leader'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedMemberIndexRouteImport } from './routes/_authenticated/member.index'
import { Route as AuthenticatedLeaderIndexRouteImport } from './routes/_authenticated/leader.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedSalesWorkflowNewRouteImport } from './routes/_authenticated/sales-workflow.new'
import { Route as AuthenticatedSalesWorkflowIdRouteImport } from './routes/_authenticated/sales-workflow.$id'
import { Route as AuthenticatedMemberWithdrawalsRouteImport } from './routes/_authenticated/member.withdrawals'
import { Route as AuthenticatedMemberWalletRouteImport } from './routes/_authenticated/member.wallet'
import { Route as AuthenticatedMemberTipsRouteImport } from './routes/_authenticated/member.tips'
import { Route as AuthenticatedMemberSettingsRouteImport } from './routes/_authenticated/member.settings'
import { Route as AuthenticatedMemberSalesRouteImport } from './routes/_authenticated/member.sales'
import { Route as AuthenticatedMemberReferralsRouteImport } from './routes/_authenticated/member.referrals'
import { Route as AuthenticatedMemberProfileRouteImport } from './routes/_authenticated/member.profile'
import { Route as AuthenticatedMemberNotificationsRouteImport } from './routes/_authenticated/member.notifications'
import { Route as AuthenticatedMemberLeaderboardRouteImport } from './routes/_authenticated/member.leaderboard'
import { Route as AuthenticatedMemberCommissionRouteImport } from './routes/_authenticated/member.commission'
import { Route as AuthenticatedMemberAnalyticsRouteImport } from './routes/_authenticated/member.analytics'
import { Route as AuthenticatedLeaderWithdrawalsRouteImport } from './routes/_authenticated/leader.withdrawals'
import { Route as AuthenticatedLeaderSettingsRouteImport } from './routes/_authenticated/leader.settings'
import { Route as AuthenticatedLeaderProjectsRouteImport } from './routes/_authenticated/leader.projects'
import { Route as AuthenticatedLeaderProfileRouteImport } from './routes/_authenticated/leader.profile'
import { Route as AuthenticatedLeaderNotificationsRouteImport } from './routes/_authenticated/leader.notifications'
import { Route as AuthenticatedLeaderMembersRouteImport } from './routes/_authenticated/leader.members'
import { Route as AuthenticatedLeaderLeaderboardRouteImport } from './routes/_authenticated/leader.leaderboard'
import { Route as AuthenticatedLeaderAnalyticsRouteImport } from './routes/_authenticated/leader.analytics'
import { Route as AuthenticatedCrmNewRouteImport } from './routes/_authenticated/crm.new'
import { Route as AuthenticatedCrmFollowupsRouteImport } from './routes/_authenticated/crm.followups'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as AuthenticatedCommissionsIdRouteImport } from './routes/_authenticated/commissions.$id'
import { Route as AuthenticatedAdminWithdrawalsRouteImport } from './routes/_authenticated/admin.withdrawals'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminTeamLeadersRouteImport } from './routes/_authenticated/admin.team-leaders'
import { Route as AuthenticatedAdminSystemRouteImport } from './routes/_authenticated/admin.system'
import { Route as AuthenticatedAdminReportsRouteImport } from './routes/_authenticated/admin.reports'
import { Route as AuthenticatedAdminProjectsRouteImport } from './routes/_authenticated/admin.projects'
import { Route as AuthenticatedAdminProfileRouteImport } from './routes/_authenticated/admin.profile'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminMembersRouteImport } from './routes/_authenticated/admin.members'
import { Route as AuthenticatedAdminMediaRouteImport } from './routes/_authenticated/admin.media'
import { Route as AuthenticatedAdminFinanceRouteImport } from './routes/_authenticated/admin.finance'
import { Route as AuthenticatedAdminCustomersRouteImport } from './routes/_authenticated/admin.customers'
import { Route as AuthenticatedAdminCommissionsRouteImport } from './routes/_authenticated/admin.commissions'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin.analytics'
import { Route as ApiPublicHooksSystemMaintenanceRouteImport } from './routes/api/public/hooks/system-maintenance'
import { Route as AuthenticatedMemberSalesIdRouteImport } from './routes/_authenticated/member.sales.$id'
import { Route as AuthenticatedLeaderMembersIdRouteImport } from './routes/_authenticated/leader.members.$id'
import { Route as AuthenticatedAdminTeamLeadersNewRouteImport } from './routes/_authenticated/admin.team-leaders.new'
import { Route as AuthenticatedAdminTeamLeadersIdRouteImport } from './routes/_authenticated/admin.team-leaders.$id'
import { Route as AuthenticatedAdminProjectsNewRouteImport } from './routes/_authenticated/admin.projects.new'
import { Route as AuthenticatedAdminProjectsIdRouteImport } from './routes/_authenticated/admin.projects.$id'
import { Route as AuthenticatedAdminMembersNewRouteImport } from './routes/_authenticated/admin.members.new'
import { Route as AuthenticatedAdminMembersIdRouteImport } from './routes/_authenticated/admin.members.$id'
import { Route as AuthenticatedAdminCustomersIdRouteImport } from './routes/_authenticated/admin.customers.$id'
import { Route as AuthenticatedAdminCmsPagesRouteImport } from './routes/_authenticated/admin.cms.pages'
import { Route as AuthenticatedAdminCmsMediaRouteImport } from './routes/_authenticated/admin.cms.media'
import { Route as AuthenticatedAdminCmsGlobalRouteImport } from './routes/_authenticated/admin.cms.global'
import { Route as AuthenticatedAdminCmsBrandRouteImport } from './routes/_authenticated/admin.cms.brand'
import { Route as AuthenticatedAdminCmsPagesIdRouteImport } from './routes/_authenticated/admin.cms.pages.$id'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRoute,
} as any)
const ErrorKindRoute = ErrorKindRouteImport.update({
  id: '/error/$kind',
  path: '/error/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesWorkflowRoute =
  AuthenticatedSalesWorkflowRouteImport.update({
    id: '/sales-workflow',
    path: '/sales-workflow',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMemberRoute = AuthenticatedMemberRouteImport.update({
  id: '/member',
  path: '/member',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeaderRoute = AuthenticatedLeaderRouteImport.update({
  id: '/leader',
  path: '/leader',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMemberIndexRoute =
  AuthenticatedMemberIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedLeaderIndexRoute =
  AuthenticatedLeaderIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSalesWorkflowNewRoute =
  AuthenticatedSalesWorkflowNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedSalesWorkflowRoute,
  } as any)
const AuthenticatedSalesWorkflowIdRoute =
  AuthenticatedSalesWorkflowIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedSalesWorkflowRoute,
  } as any)
const AuthenticatedMemberWithdrawalsRoute =
  AuthenticatedMemberWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberWalletRoute =
  AuthenticatedMemberWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberTipsRoute = AuthenticatedMemberTipsRouteImport.update({
  id: '/tips',
  path: '/tips',
  getParentRoute: () => AuthenticatedMemberRoute,
} as any)
const AuthenticatedMemberSettingsRoute =
  AuthenticatedMemberSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberSalesRoute =
  AuthenticatedMemberSalesRouteImport.update({
    id: '/sales',
    path: '/sales',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberReferralsRoute =
  AuthenticatedMemberReferralsRouteImport.update({
    id: '/referrals',
    path: '/referrals',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberProfileRoute =
  AuthenticatedMemberProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberNotificationsRoute =
  AuthenticatedMemberNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberLeaderboardRoute =
  AuthenticatedMemberLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberCommissionRoute =
  AuthenticatedMemberCommissionRouteImport.update({
    id: '/commission',
    path: '/commission',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedMemberAnalyticsRoute =
  AuthenticatedMemberAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedMemberRoute,
  } as any)
const AuthenticatedLeaderWithdrawalsRoute =
  AuthenticatedLeaderWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderSettingsRoute =
  AuthenticatedLeaderSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderProjectsRoute =
  AuthenticatedLeaderProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderProfileRoute =
  AuthenticatedLeaderProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderNotificationsRoute =
  AuthenticatedLeaderNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderMembersRoute =
  AuthenticatedLeaderMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderLeaderboardRoute =
  AuthenticatedLeaderLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedLeaderAnalyticsRoute =
  AuthenticatedLeaderAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedLeaderRoute,
  } as any)
const AuthenticatedCrmNewRoute = AuthenticatedCrmNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmFollowupsRoute =
  AuthenticatedCrmFollowupsRouteImport.update({
    id: '/followups',
    path: '/followups',
    getParentRoute: () => AuthenticatedCrmRoute,
  } as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCommissionsIdRoute =
  AuthenticatedCommissionsIdRouteImport.update({
    id: '/commissions/$id',
    path: '/commissions/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminWithdrawalsRoute =
  AuthenticatedAdminWithdrawalsRouteImport.update({
    id: '/withdrawals',
    path: '/withdrawals',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTeamLeadersRoute =
  AuthenticatedAdminTeamLeadersRouteImport.update({
    id: '/team-leaders',
    path: '/team-leaders',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSystemRoute =
  AuthenticatedAdminSystemRouteImport.update({
    id: '/system',
    path: '/system',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminReportsRoute =
  AuthenticatedAdminReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProjectsRoute =
  AuthenticatedAdminProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminProfileRoute =
  AuthenticatedAdminProfileRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMembersRoute =
  AuthenticatedAdminMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMediaRoute = AuthenticatedAdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFinanceRoute =
  AuthenticatedAdminFinanceRouteImport.update({
    id: '/finance',
    path: '/finance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCustomersRoute =
  AuthenticatedAdminCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCommissionsRoute =
  AuthenticatedAdminCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const ApiPublicHooksSystemMaintenanceRoute =
  ApiPublicHooksSystemMaintenanceRouteImport.update({
    id: '/api/public/hooks/system-maintenance',
    path: '/api/public/hooks/system-maintenance',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedMemberSalesIdRoute =
  AuthenticatedMemberSalesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedMemberSalesRoute,
  } as any)
const AuthenticatedLeaderMembersIdRoute =
  AuthenticatedLeaderMembersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedLeaderMembersRoute,
  } as any)
const AuthenticatedAdminTeamLeadersNewRoute =
  AuthenticatedAdminTeamLeadersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminTeamLeadersRoute,
  } as any)
const AuthenticatedAdminTeamLeadersIdRoute =
  AuthenticatedAdminTeamLeadersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminTeamLeadersRoute,
  } as any)
const AuthenticatedAdminProjectsNewRoute =
  AuthenticatedAdminProjectsNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedAdminProjectsIdRoute =
  AuthenticatedAdminProjectsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminProjectsRoute,
  } as any)
const AuthenticatedAdminMembersNewRoute =
  AuthenticatedAdminMembersNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => AuthenticatedAdminMembersRoute,
  } as any)
const AuthenticatedAdminMembersIdRoute =
  AuthenticatedAdminMembersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminMembersRoute,
  } as any)
const AuthenticatedAdminCustomersIdRoute =
  AuthenticatedAdminCustomersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCustomersRoute,
  } as any)
const AuthenticatedAdminCmsPagesRoute =
  AuthenticatedAdminCmsPagesRouteImport.update({
    id: '/cms/pages',
    path: '/cms/pages',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsMediaRoute =
  AuthenticatedAdminCmsMediaRouteImport.update({
    id: '/cms/media',
    path: '/cms/media',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsGlobalRoute =
  AuthenticatedAdminCmsGlobalRouteImport.update({
    id: '/cms/global',
    path: '/cms/global',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsBrandRoute =
  AuthenticatedAdminCmsBrandRouteImport.update({
    id: '/cms/brand',
    path: '/cms/brand',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCmsPagesIdRoute =
  AuthenticatedAdminCmsPagesIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminCmsPagesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leader': typeof AuthenticatedLeaderRouteWithChildren
  '/member': typeof AuthenticatedMemberRouteWithChildren
  '/sales-workflow': typeof AuthenticatedSalesWorkflowRouteWithChildren
  '/error/$kind': typeof ErrorKindRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/team-leaders': typeof AuthenticatedAdminTeamLeadersRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/commissions/$id': typeof AuthenticatedCommissionsIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/crm/new': typeof AuthenticatedCrmNewRoute
  '/leader/analytics': typeof AuthenticatedLeaderAnalyticsRoute
  '/leader/leaderboard': typeof AuthenticatedLeaderLeaderboardRoute
  '/leader/members': typeof AuthenticatedLeaderMembersRouteWithChildren
  '/leader/notifications': typeof AuthenticatedLeaderNotificationsRoute
  '/leader/profile': typeof AuthenticatedLeaderProfileRoute
  '/leader/projects': typeof AuthenticatedLeaderProjectsRoute
  '/leader/settings': typeof AuthenticatedLeaderSettingsRoute
  '/leader/withdrawals': typeof AuthenticatedLeaderWithdrawalsRoute
  '/member/analytics': typeof AuthenticatedMemberAnalyticsRoute
  '/member/commission': typeof AuthenticatedMemberCommissionRoute
  '/member/leaderboard': typeof AuthenticatedMemberLeaderboardRoute
  '/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/member/profile': typeof AuthenticatedMemberProfileRoute
  '/member/referrals': typeof AuthenticatedMemberReferralsRoute
  '/member/sales': typeof AuthenticatedMemberSalesRouteWithChildren
  '/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/member/tips': typeof AuthenticatedMemberTipsRoute
  '/member/wallet': typeof AuthenticatedMemberWalletRoute
  '/member/withdrawals': typeof AuthenticatedMemberWithdrawalsRoute
  '/sales-workflow/$id': typeof AuthenticatedSalesWorkflowIdRoute
  '/sales-workflow/new': typeof AuthenticatedSalesWorkflowNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/leader/': typeof AuthenticatedLeaderIndexRoute
  '/member/': typeof AuthenticatedMemberIndexRoute
  '/admin/cms/brand': typeof AuthenticatedAdminCmsBrandRoute
  '/admin/cms/global': typeof AuthenticatedAdminCmsGlobalRoute
  '/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRouteWithChildren
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/admin/team-leaders/$id': typeof AuthenticatedAdminTeamLeadersIdRoute
  '/admin/team-leaders/new': typeof AuthenticatedAdminTeamLeadersNewRoute
  '/leader/members/$id': typeof AuthenticatedLeaderMembersIdRoute
  '/member/sales/$id': typeof AuthenticatedMemberSalesIdRoute
  '/api/public/hooks/system-maintenance': typeof ApiPublicHooksSystemMaintenanceRoute
  '/admin/cms/pages/$id': typeof AuthenticatedAdminCmsPagesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/sales-workflow': typeof AuthenticatedSalesWorkflowRouteWithChildren
  '/error/$kind': typeof ErrorKindRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects': typeof ProjectsIndexRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/admin/media': typeof AuthenticatedAdminMediaRoute
  '/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/admin/system': typeof AuthenticatedAdminSystemRoute
  '/admin/team-leaders': typeof AuthenticatedAdminTeamLeadersRouteWithChildren
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/commissions/$id': typeof AuthenticatedCommissionsIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/crm/new': typeof AuthenticatedCrmNewRoute
  '/leader/analytics': typeof AuthenticatedLeaderAnalyticsRoute
  '/leader/leaderboard': typeof AuthenticatedLeaderLeaderboardRoute
  '/leader/members': typeof AuthenticatedLeaderMembersRouteWithChildren
  '/leader/notifications': typeof AuthenticatedLeaderNotificationsRoute
  '/leader/profile': typeof AuthenticatedLeaderProfileRoute
  '/leader/projects': typeof AuthenticatedLeaderProjectsRoute
  '/leader/settings': typeof AuthenticatedLeaderSettingsRoute
  '/leader/withdrawals': typeof AuthenticatedLeaderWithdrawalsRoute
  '/member/analytics': typeof AuthenticatedMemberAnalyticsRoute
  '/member/commission': typeof AuthenticatedMemberCommissionRoute
  '/member/leaderboard': typeof AuthenticatedMemberLeaderboardRoute
  '/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/member/profile': typeof AuthenticatedMemberProfileRoute
  '/member/referrals': typeof AuthenticatedMemberReferralsRoute
  '/member/sales': typeof AuthenticatedMemberSalesRouteWithChildren
  '/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/member/tips': typeof AuthenticatedMemberTipsRoute
  '/member/wallet': typeof AuthenticatedMemberWalletRoute
  '/member/withdrawals': typeof AuthenticatedMemberWithdrawalsRoute
  '/sales-workflow/$id': typeof AuthenticatedSalesWorkflowIdRoute
  '/sales-workflow/new': typeof AuthenticatedSalesWorkflowNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/leader': typeof AuthenticatedLeaderIndexRoute
  '/member': typeof AuthenticatedMemberIndexRoute
  '/admin/cms/brand': typeof AuthenticatedAdminCmsBrandRoute
  '/admin/cms/global': typeof AuthenticatedAdminCmsGlobalRoute
  '/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRouteWithChildren
  '/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/admin/team-leaders/$id': typeof AuthenticatedAdminTeamLeadersIdRoute
  '/admin/team-leaders/new': typeof AuthenticatedAdminTeamLeadersNewRoute
  '/leader/members/$id': typeof AuthenticatedLeaderMembersIdRoute
  '/member/sales/$id': typeof AuthenticatedMemberSalesIdRoute
  '/api/public/hooks/system-maintenance': typeof ApiPublicHooksSystemMaintenanceRoute
  '/admin/cms/pages/$id': typeof AuthenticatedAdminCmsPagesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin-login': typeof AdminLoginRoute
  '/auth': typeof AuthRoute
  '/projects': typeof ProjectsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leader': typeof AuthenticatedLeaderRouteWithChildren
  '/_authenticated/member': typeof AuthenticatedMemberRouteWithChildren
  '/_authenticated/sales-workflow': typeof AuthenticatedSalesWorkflowRouteWithChildren
  '/error/$kind': typeof ErrorKindRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/projects/': typeof ProjectsIndexRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/commissions': typeof AuthenticatedAdminCommissionsRoute
  '/_authenticated/admin/customers': typeof AuthenticatedAdminCustomersRouteWithChildren
  '/_authenticated/admin/finance': typeof AuthenticatedAdminFinanceRoute
  '/_authenticated/admin/media': typeof AuthenticatedAdminMediaRoute
  '/_authenticated/admin/members': typeof AuthenticatedAdminMembersRouteWithChildren
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/profile': typeof AuthenticatedAdminProfileRoute
  '/_authenticated/admin/projects': typeof AuthenticatedAdminProjectsRouteWithChildren
  '/_authenticated/admin/reports': typeof AuthenticatedAdminReportsRoute
  '/_authenticated/admin/system': typeof AuthenticatedAdminSystemRoute
  '/_authenticated/admin/team-leaders': typeof AuthenticatedAdminTeamLeadersRouteWithChildren
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/admin/withdrawals': typeof AuthenticatedAdminWithdrawalsRoute
  '/_authenticated/commissions/$id': typeof AuthenticatedCommissionsIdRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/crm/followups': typeof AuthenticatedCrmFollowupsRoute
  '/_authenticated/crm/new': typeof AuthenticatedCrmNewRoute
  '/_authenticated/leader/analytics': typeof AuthenticatedLeaderAnalyticsRoute
  '/_authenticated/leader/leaderboard': typeof AuthenticatedLeaderLeaderboardRoute
  '/_authenticated/leader/members': typeof AuthenticatedLeaderMembersRouteWithChildren
  '/_authenticated/leader/notifications': typeof AuthenticatedLeaderNotificationsRoute
  '/_authenticated/leader/profile': typeof AuthenticatedLeaderProfileRoute
  '/_authenticated/leader/projects': typeof AuthenticatedLeaderProjectsRoute
  '/_authenticated/leader/settings': typeof AuthenticatedLeaderSettingsRoute
  '/_authenticated/leader/withdrawals': typeof AuthenticatedLeaderWithdrawalsRoute
  '/_authenticated/member/analytics': typeof AuthenticatedMemberAnalyticsRoute
  '/_authenticated/member/commission': typeof AuthenticatedMemberCommissionRoute
  '/_authenticated/member/leaderboard': typeof AuthenticatedMemberLeaderboardRoute
  '/_authenticated/member/notifications': typeof AuthenticatedMemberNotificationsRoute
  '/_authenticated/member/profile': typeof AuthenticatedMemberProfileRoute
  '/_authenticated/member/referrals': typeof AuthenticatedMemberReferralsRoute
  '/_authenticated/member/sales': typeof AuthenticatedMemberSalesRouteWithChildren
  '/_authenticated/member/settings': typeof AuthenticatedMemberSettingsRoute
  '/_authenticated/member/tips': typeof AuthenticatedMemberTipsRoute
  '/_authenticated/member/wallet': typeof AuthenticatedMemberWalletRoute
  '/_authenticated/member/withdrawals': typeof AuthenticatedMemberWithdrawalsRoute
  '/_authenticated/sales-workflow/$id': typeof AuthenticatedSalesWorkflowIdRoute
  '/_authenticated/sales-workflow/new': typeof AuthenticatedSalesWorkflowNewRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/leader/': typeof AuthenticatedLeaderIndexRoute
  '/_authenticated/member/': typeof AuthenticatedMemberIndexRoute
  '/_authenticated/admin/cms/brand': typeof AuthenticatedAdminCmsBrandRoute
  '/_authenticated/admin/cms/global': typeof AuthenticatedAdminCmsGlobalRoute
  '/_authenticated/admin/cms/media': typeof AuthenticatedAdminCmsMediaRoute
  '/_authenticated/admin/cms/pages': typeof AuthenticatedAdminCmsPagesRouteWithChildren
  '/_authenticated/admin/customers/$id': typeof AuthenticatedAdminCustomersIdRoute
  '/_authenticated/admin/members/$id': typeof AuthenticatedAdminMembersIdRoute
  '/_authenticated/admin/members/new': typeof AuthenticatedAdminMembersNewRoute
  '/_authenticated/admin/projects/$id': typeof AuthenticatedAdminProjectsIdRoute
  '/_authenticated/admin/projects/new': typeof AuthenticatedAdminProjectsNewRoute
  '/_authenticated/admin/team-leaders/$id': typeof AuthenticatedAdminTeamLeadersIdRoute
  '/_authenticated/admin/team-leaders/new': typeof AuthenticatedAdminTeamLeadersNewRoute
  '/_authenticated/leader/members/$id': typeof AuthenticatedLeaderMembersIdRoute
  '/_authenticated/member/sales/$id': typeof AuthenticatedMemberSalesIdRoute
  '/api/public/hooks/system-maintenance': typeof ApiPublicHooksSystemMaintenanceRoute
  '/_authenticated/admin/cms/pages/$id': typeof AuthenticatedAdminCmsPagesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/projects'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/admin'
    | '/crm'
    | '/dashboard'
    | '/leader'
    | '/member'
    | '/sales-workflow'
    | '/error/$kind'
    | '/projects/$slug'
    | '/projects/'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/system'
    | '/admin/team-leaders'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/commissions/$id'
    | '/crm/$id'
    | '/crm/followups'
    | '/crm/new'
    | '/leader/analytics'
    | '/leader/leaderboard'
    | '/leader/members'
    | '/leader/notifications'
    | '/leader/profile'
    | '/leader/projects'
    | '/leader/settings'
    | '/leader/withdrawals'
    | '/member/analytics'
    | '/member/commission'
    | '/member/leaderboard'
    | '/member/notifications'
    | '/member/profile'
    | '/member/referrals'
    | '/member/sales'
    | '/member/settings'
    | '/member/tips'
    | '/member/wallet'
    | '/member/withdrawals'
    | '/sales-workflow/$id'
    | '/sales-workflow/new'
    | '/api/public/health'
    | '/admin/'
    | '/leader/'
    | '/member/'
    | '/admin/cms/brand'
    | '/admin/cms/global'
    | '/admin/cms/media'
    | '/admin/cms/pages'
    | '/admin/customers/$id'
    | '/admin/members/$id'
    | '/admin/members/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/team-leaders/$id'
    | '/admin/team-leaders/new'
    | '/leader/members/$id'
    | '/member/sales/$id'
    | '/api/public/hooks/system-maintenance'
    | '/admin/cms/pages/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/auth'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/crm'
    | '/dashboard'
    | '/sales-workflow'
    | '/error/$kind'
    | '/projects/$slug'
    | '/projects'
    | '/admin/analytics'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/finance'
    | '/admin/media'
    | '/admin/members'
    | '/admin/notifications'
    | '/admin/profile'
    | '/admin/projects'
    | '/admin/reports'
    | '/admin/system'
    | '/admin/team-leaders'
    | '/admin/users'
    | '/admin/withdrawals'
    | '/commissions/$id'
    | '/crm/$id'
    | '/crm/followups'
    | '/crm/new'
    | '/leader/analytics'
    | '/leader/leaderboard'
    | '/leader/members'
    | '/leader/notifications'
    | '/leader/profile'
    | '/leader/projects'
    | '/leader/settings'
    | '/leader/withdrawals'
    | '/member/analytics'
    | '/member/commission'
    | '/member/leaderboard'
    | '/member/notifications'
    | '/member/profile'
    | '/member/referrals'
    | '/member/sales'
    | '/member/settings'
    | '/member/tips'
    | '/member/wallet'
    | '/member/withdrawals'
    | '/sales-workflow/$id'
    | '/sales-workflow/new'
    | '/api/public/health'
    | '/admin'
    | '/leader'
    | '/member'
    | '/admin/cms/brand'
    | '/admin/cms/global'
    | '/admin/cms/media'
    | '/admin/cms/pages'
    | '/admin/customers/$id'
    | '/admin/members/$id'
    | '/admin/members/new'
    | '/admin/projects/$id'
    | '/admin/projects/new'
    | '/admin/team-leaders/$id'
    | '/admin/team-leaders/new'
    | '/leader/members/$id'
    | '/member/sales/$id'
    | '/api/public/hooks/system-maintenance'
    | '/admin/cms/pages/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin-login'
    | '/auth'
    | '/projects'
    | '/sitemap.xml'
    | '/unauthorized'
    | '/_authenticated/admin'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/leader'
    | '/_authenticated/member'
    | '/_authenticated/sales-workflow'
    | '/error/$kind'
    | '/projects/$slug'
    | '/projects/'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/commissions'
    | '/_authenticated/admin/customers'
    | '/_authenticated/admin/finance'
    | '/_authenticated/admin/media'
    | '/_authenticated/admin/members'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/profile'
    | '/_authenticated/admin/projects'
    | '/_authenticated/admin/reports'
    | '/_authenticated/admin/system'
    | '/_authenticated/admin/team-leaders'
    | '/_authenticated/admin/users'
    | '/_authenticated/admin/withdrawals'
    | '/_authenticated/commissions/$id'
    | '/_authenticated/crm/$id'
    | '/_authenticated/crm/followups'
    | '/_authenticated/crm/new'
    | '/_authenticated/leader/analytics'
    | '/_authenticated/leader/leaderboard'
    | '/_authenticated/leader/members'
    | '/_authenticated/leader/notifications'
    | '/_authenticated/leader/profile'
    | '/_authenticated/leader/projects'
    | '/_authenticated/leader/settings'
    | '/_authenticated/leader/withdrawals'
    | '/_authenticated/member/analytics'
    | '/_authenticated/member/commission'
    | '/_authenticated/member/leaderboard'
    | '/_authenticated/member/notifications'
    | '/_authenticated/member/profile'
    | '/_authenticated/member/referrals'
    | '/_authenticated/member/sales'
    | '/_authenticated/member/settings'
    | '/_authenticated/member/tips'
    | '/_authenticated/member/wallet'
    | '/_authenticated/member/withdrawals'
    | '/_authenticated/sales-workflow/$id'
    | '/_authenticated/sales-workflow/new'
    | '/api/public/health'
    | '/_authenticated/admin/'
    | '/_authenticated/leader/'
    | '/_authenticated/member/'
    | '/_authenticated/admin/cms/brand'
    | '/_authenticated/admin/cms/global'
    | '/_authenticated/admin/cms/media'
    | '/_authenticated/admin/cms/pages'
    | '/_authenticated/admin/customers/$id'
    | '/_authenticated/admin/members/$id'
    | '/_authenticated/admin/members/new'
    | '/_authenticated/admin/projects/$id'
    | '/_authenticated/admin/projects/new'
    | '/_authenticated/admin/team-leaders/$id'
    | '/_authenticated/admin/team-leaders/new'
    | '/_authenticated/leader/members/$id'
    | '/_authenticated/member/sales/$id'
    | '/api/public/hooks/system-maintenance'
    | '/_authenticated/admin/cms/pages/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AuthRoute: typeof AuthRoute
  ProjectsRoute: typeof ProjectsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  ErrorKindRoute: typeof ErrorKindRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicHooksSystemMaintenanceRoute: typeof ApiPublicHooksSystemMaintenanceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/error/$kind': {
      id: '/error/$kind'
      path: '/error/$kind'
      fullPath: '/error/$kind'
      preLoaderRoute: typeof ErrorKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-workflow': {
      id: '/_authenticated/sales-workflow'
      path: '/sales-workflow'
      fullPath: '/sales-workflow'
      preLoaderRoute: typeof AuthenticatedSalesWorkflowRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member': {
      id: '/_authenticated/member'
      path: '/member'
      fullPath: '/member'
      preLoaderRoute: typeof AuthenticatedMemberRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leader': {
      id: '/_authenticated/leader'
      path: '/leader'
      fullPath: '/leader'
      preLoaderRoute: typeof AuthenticatedLeaderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/member/': {
      id: '/_authenticated/member/'
      path: '/'
      fullPath: '/member/'
      preLoaderRoute: typeof AuthenticatedMemberIndexRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/leader/': {
      id: '/_authenticated/leader/'
      path: '/'
      fullPath: '/leader/'
      preLoaderRoute: typeof AuthenticatedLeaderIndexRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/sales-workflow/new': {
      id: '/_authenticated/sales-workflow/new'
      path: '/new'
      fullPath: '/sales-workflow/new'
      preLoaderRoute: typeof AuthenticatedSalesWorkflowNewRouteImport
      parentRoute: typeof AuthenticatedSalesWorkflowRoute
    }
    '/_authenticated/sales-workflow/$id': {
      id: '/_authenticated/sales-workflow/$id'
      path: '/$id'
      fullPath: '/sales-workflow/$id'
      preLoaderRoute: typeof AuthenticatedSalesWorkflowIdRouteImport
      parentRoute: typeof AuthenticatedSalesWorkflowRoute
    }
    '/_authenticated/member/withdrawals': {
      id: '/_authenticated/member/withdrawals'
      path: '/withdrawals'
      fullPath: '/member/withdrawals'
      preLoaderRoute: typeof AuthenticatedMemberWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/wallet': {
      id: '/_authenticated/member/wallet'
      path: '/wallet'
      fullPath: '/member/wallet'
      preLoaderRoute: typeof AuthenticatedMemberWalletRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/tips': {
      id: '/_authenticated/member/tips'
      path: '/tips'
      fullPath: '/member/tips'
      preLoaderRoute: typeof AuthenticatedMemberTipsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/settings': {
      id: '/_authenticated/member/settings'
      path: '/settings'
      fullPath: '/member/settings'
      preLoaderRoute: typeof AuthenticatedMemberSettingsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/sales': {
      id: '/_authenticated/member/sales'
      path: '/sales'
      fullPath: '/member/sales'
      preLoaderRoute: typeof AuthenticatedMemberSalesRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/referrals': {
      id: '/_authenticated/member/referrals'
      path: '/referrals'
      fullPath: '/member/referrals'
      preLoaderRoute: typeof AuthenticatedMemberReferralsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/profile': {
      id: '/_authenticated/member/profile'
      path: '/profile'
      fullPath: '/member/profile'
      preLoaderRoute: typeof AuthenticatedMemberProfileRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/notifications': {
      id: '/_authenticated/member/notifications'
      path: '/notifications'
      fullPath: '/member/notifications'
      preLoaderRoute: typeof AuthenticatedMemberNotificationsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/leaderboard': {
      id: '/_authenticated/member/leaderboard'
      path: '/leaderboard'
      fullPath: '/member/leaderboard'
      preLoaderRoute: typeof AuthenticatedMemberLeaderboardRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/commission': {
      id: '/_authenticated/member/commission'
      path: '/commission'
      fullPath: '/member/commission'
      preLoaderRoute: typeof AuthenticatedMemberCommissionRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/member/analytics': {
      id: '/_authenticated/member/analytics'
      path: '/analytics'
      fullPath: '/member/analytics'
      preLoaderRoute: typeof AuthenticatedMemberAnalyticsRouteImport
      parentRoute: typeof AuthenticatedMemberRoute
    }
    '/_authenticated/leader/withdrawals': {
      id: '/_authenticated/leader/withdrawals'
      path: '/withdrawals'
      fullPath: '/leader/withdrawals'
      preLoaderRoute: typeof AuthenticatedLeaderWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/settings': {
      id: '/_authenticated/leader/settings'
      path: '/settings'
      fullPath: '/leader/settings'
      preLoaderRoute: typeof AuthenticatedLeaderSettingsRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/projects': {
      id: '/_authenticated/leader/projects'
      path: '/projects'
      fullPath: '/leader/projects'
      preLoaderRoute: typeof AuthenticatedLeaderProjectsRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/profile': {
      id: '/_authenticated/leader/profile'
      path: '/profile'
      fullPath: '/leader/profile'
      preLoaderRoute: typeof AuthenticatedLeaderProfileRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/notifications': {
      id: '/_authenticated/leader/notifications'
      path: '/notifications'
      fullPath: '/leader/notifications'
      preLoaderRoute: typeof AuthenticatedLeaderNotificationsRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/members': {
      id: '/_authenticated/leader/members'
      path: '/members'
      fullPath: '/leader/members'
      preLoaderRoute: typeof AuthenticatedLeaderMembersRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/leaderboard': {
      id: '/_authenticated/leader/leaderboard'
      path: '/leaderboard'
      fullPath: '/leader/leaderboard'
      preLoaderRoute: typeof AuthenticatedLeaderLeaderboardRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/leader/analytics': {
      id: '/_authenticated/leader/analytics'
      path: '/analytics'
      fullPath: '/leader/analytics'
      preLoaderRoute: typeof AuthenticatedLeaderAnalyticsRouteImport
      parentRoute: typeof AuthenticatedLeaderRoute
    }
    '/_authenticated/crm/new': {
      id: '/_authenticated/crm/new'
      path: '/new'
      fullPath: '/crm/new'
      preLoaderRoute: typeof AuthenticatedCrmNewRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/followups': {
      id: '/_authenticated/crm/followups'
      path: '/followups'
      fullPath: '/crm/followups'
      preLoaderRoute: typeof AuthenticatedCrmFollowupsRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/commissions/$id': {
      id: '/_authenticated/commissions/$id'
      path: '/commissions/$id'
      fullPath: '/commissions/$id'
      preLoaderRoute: typeof AuthenticatedCommissionsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/withdrawals': {
      id: '/_authenticated/admin/withdrawals'
      path: '/withdrawals'
      fullPath: '/admin/withdrawals'
      preLoaderRoute: typeof AuthenticatedAdminWithdrawalsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/team-leaders': {
      id: '/_authenticated/admin/team-leaders'
      path: '/team-leaders'
      fullPath: '/admin/team-leaders'
      preLoaderRoute: typeof AuthenticatedAdminTeamLeadersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/system': {
      id: '/_authenticated/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AuthenticatedAdminSystemRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/reports': {
      id: '/_authenticated/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AuthenticatedAdminReportsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/projects': {
      id: '/_authenticated/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AuthenticatedAdminProjectsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/profile': {
      id: '/_authenticated/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AuthenticatedAdminProfileRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/members': {
      id: '/_authenticated/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AuthenticatedAdminMembersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/media': {
      id: '/_authenticated/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AuthenticatedAdminMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/finance': {
      id: '/_authenticated/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AuthenticatedAdminFinanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/customers': {
      id: '/_authenticated/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AuthenticatedAdminCustomersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/commissions': {
      id: '/_authenticated/admin/commissions'
      path: '/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AuthenticatedAdminCommissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/hooks/system-maintenance': {
      id: '/api/public/hooks/system-maintenance'
      path: '/api/public/hooks/system-maintenance'
      fullPath: '/api/public/hooks/system-maintenance'
      preLoaderRoute: typeof ApiPublicHooksSystemMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/member/sales/$id': {
      id: '/_authenticated/member/sales/$id'
      path: '/$id'
      fullPath: '/member/sales/$id'
      preLoaderRoute: typeof AuthenticatedMemberSalesIdRouteImport
      parentRoute: typeof AuthenticatedMemberSalesRoute
    }
    '/_authenticated/leader/members/$id': {
      id: '/_authenticated/leader/members/$id'
      path: '/$id'
      fullPath: '/leader/members/$id'
      preLoaderRoute: typeof AuthenticatedLeaderMembersIdRouteImport
      parentRoute: typeof AuthenticatedLeaderMembersRoute
    }
    '/_authenticated/admin/team-leaders/new': {
      id: '/_authenticated/admin/team-leaders/new'
      path: '/new'
      fullPath: '/admin/team-leaders/new'
      preLoaderRoute: typeof AuthenticatedAdminTeamLeadersNewRouteImport
      parentRoute: typeof AuthenticatedAdminTeamLeadersRoute
    }
    '/_authenticated/admin/team-leaders/$id': {
      id: '/_authenticated/admin/team-leaders/$id'
      path: '/$id'
      fullPath: '/admin/team-leaders/$id'
      preLoaderRoute: typeof AuthenticatedAdminTeamLeadersIdRouteImport
      parentRoute: typeof AuthenticatedAdminTeamLeadersRoute
    }
    '/_authenticated/admin/projects/new': {
      id: '/_authenticated/admin/projects/new'
      path: '/new'
      fullPath: '/admin/projects/new'
      preLoaderRoute: typeof AuthenticatedAdminProjectsNewRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/admin/projects/$id': {
      id: '/_authenticated/admin/projects/$id'
      path: '/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AuthenticatedAdminProjectsIdRouteImport
      parentRoute: typeof AuthenticatedAdminProjectsRoute
    }
    '/_authenticated/admin/members/new': {
      id: '/_authenticated/admin/members/new'
      path: '/new'
      fullPath: '/admin/members/new'
      preLoaderRoute: typeof AuthenticatedAdminMembersNewRouteImport
      parentRoute: typeof AuthenticatedAdminMembersRoute
    }
    '/_authenticated/admin/members/$id': {
      id: '/_authenticated/admin/members/$id'
      path: '/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AuthenticatedAdminMembersIdRouteImport
      parentRoute: typeof AuthenticatedAdminMembersRoute
    }
    '/_authenticated/admin/customers/$id': {
      id: '/_authenticated/admin/customers/$id'
      path: '/$id'
      fullPath: '/admin/customers/$id'
      preLoaderRoute: typeof AuthenticatedAdminCustomersIdRouteImport
      parentRoute: typeof AuthenticatedAdminCustomersRoute
    }
    '/_authenticated/admin/cms/pages': {
      id: '/_authenticated/admin/cms/pages'
      path: '/cms/pages'
      fullPath: '/admin/cms/pages'
      preLoaderRoute: typeof AuthenticatedAdminCmsPagesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/media': {
      id: '/_authenticated/admin/cms/media'
      path: '/cms/media'
      fullPath: '/admin/cms/media'
      preLoaderRoute: typeof AuthenticatedAdminCmsMediaRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/global': {
      id: '/_authenticated/admin/cms/global'
      path: '/cms/global'
      fullPath: '/admin/cms/global'
      preLoaderRoute: typeof AuthenticatedAdminCmsGlobalRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/brand': {
      id: '/_authenticated/admin/cms/brand'
      path: '/cms/brand'
      fullPath: '/admin/cms/brand'
      preLoaderRoute: typeof AuthenticatedAdminCmsBrandRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/cms/pages/$id': {
      id: '/_authenticated/admin/cms/pages/$id'
      path: '/$id'
      fullPath: '/admin/cms/pages/$id'
      preLoaderRoute: typeof AuthenticatedAdminCmsPagesIdRouteImport
      parentRoute: typeof AuthenticatedAdminCmsPagesRoute
    }
  }
}

interface AuthenticatedAdminCustomersRouteChildren {
  AuthenticatedAdminCustomersIdRoute: typeof AuthenticatedAdminCustomersIdRoute
}

const AuthenticatedAdminCustomersRouteChildren: AuthenticatedAdminCustomersRouteChildren =
  {
    AuthenticatedAdminCustomersIdRoute: AuthenticatedAdminCustomersIdRoute,
  }

const AuthenticatedAdminCustomersRouteWithChildren =
  AuthenticatedAdminCustomersRoute._addFileChildren(
    AuthenticatedAdminCustomersRouteChildren,
  )

interface AuthenticatedAdminMembersRouteChildren {
  AuthenticatedAdminMembersIdRoute: typeof AuthenticatedAdminMembersIdRoute
  AuthenticatedAdminMembersNewRoute: typeof AuthenticatedAdminMembersNewRoute
}

const AuthenticatedAdminMembersRouteChildren: AuthenticatedAdminMembersRouteChildren =
  {
    AuthenticatedAdminMembersIdRoute: AuthenticatedAdminMembersIdRoute,
    AuthenticatedAdminMembersNewRoute: AuthenticatedAdminMembersNewRoute,
  }

const AuthenticatedAdminMembersRouteWithChildren =
  AuthenticatedAdminMembersRoute._addFileChildren(
    AuthenticatedAdminMembersRouteChildren,
  )

interface AuthenticatedAdminProjectsRouteChildren {
  AuthenticatedAdminProjectsIdRoute: typeof AuthenticatedAdminProjectsIdRoute
  AuthenticatedAdminProjectsNewRoute: typeof AuthenticatedAdminProjectsNewRoute
}

const AuthenticatedAdminProjectsRouteChildren: AuthenticatedAdminProjectsRouteChildren =
  {
    AuthenticatedAdminProjectsIdRoute: AuthenticatedAdminProjectsIdRoute,
    AuthenticatedAdminProjectsNewRoute: AuthenticatedAdminProjectsNewRoute,
  }

const AuthenticatedAdminProjectsRouteWithChildren =
  AuthenticatedAdminProjectsRoute._addFileChildren(
    AuthenticatedAdminProjectsRouteChildren,
  )

interface AuthenticatedAdminTeamLeadersRouteChildren {
  AuthenticatedAdminTeamLeadersIdRoute: typeof AuthenticatedAdminTeamLeadersIdRoute
  AuthenticatedAdminTeamLeadersNewRoute: typeof AuthenticatedAdminTeamLeadersNewRoute
}

const AuthenticatedAdminTeamLeadersRouteChildren: AuthenticatedAdminTeamLeadersRouteChildren =
  {
    AuthenticatedAdminTeamLeadersIdRoute: AuthenticatedAdminTeamLeadersIdRoute,
    AuthenticatedAdminTeamLeadersNewRoute:
      AuthenticatedAdminTeamLeadersNewRoute,
  }

const AuthenticatedAdminTeamLeadersRouteWithChildren =
  AuthenticatedAdminTeamLeadersRoute._addFileChildren(
    AuthenticatedAdminTeamLeadersRouteChildren,
  )

interface AuthenticatedAdminCmsPagesRouteChildren {
  AuthenticatedAdminCmsPagesIdRoute: typeof AuthenticatedAdminCmsPagesIdRoute
}

const AuthenticatedAdminCmsPagesRouteChildren: AuthenticatedAdminCmsPagesRouteChildren =
  {
    AuthenticatedAdminCmsPagesIdRoute: AuthenticatedAdminCmsPagesIdRoute,
  }

const AuthenticatedAdminCmsPagesRouteWithChildren =
  AuthenticatedAdminCmsPagesRoute._addFileChildren(
    AuthenticatedAdminCmsPagesRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminCommissionsRoute: typeof AuthenticatedAdminCommissionsRoute
  AuthenticatedAdminCustomersRoute: typeof AuthenticatedAdminCustomersRouteWithChildren
  AuthenticatedAdminFinanceRoute: typeof AuthenticatedAdminFinanceRoute
  AuthenticatedAdminMediaRoute: typeof AuthenticatedAdminMediaRoute
  AuthenticatedAdminMembersRoute: typeof AuthenticatedAdminMembersRouteWithChildren
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminProfileRoute: typeof AuthenticatedAdminProfileRoute
  AuthenticatedAdminProjectsRoute: typeof AuthenticatedAdminProjectsRouteWithChildren
  AuthenticatedAdminReportsRoute: typeof AuthenticatedAdminReportsRoute
  AuthenticatedAdminSystemRoute: typeof AuthenticatedAdminSystemRoute
  AuthenticatedAdminTeamLeadersRoute: typeof AuthenticatedAdminTeamLeadersRouteWithChildren
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminWithdrawalsRoute: typeof AuthenticatedAdminWithdrawalsRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminCmsBrandRoute: typeof AuthenticatedAdminCmsBrandRoute
  AuthenticatedAdminCmsGlobalRoute: typeof AuthenticatedAdminCmsGlobalRoute
  AuthenticatedAdminCmsMediaRoute: typeof AuthenticatedAdminCmsMediaRoute
  AuthenticatedAdminCmsPagesRoute: typeof AuthenticatedAdminCmsPagesRouteWithChildren
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
  AuthenticatedAdminCommissionsRoute: AuthenticatedAdminCommissionsRoute,
  AuthenticatedAdminCustomersRoute:
    AuthenticatedAdminCustomersRouteWithChildren,
  AuthenticatedAdminFinanceRoute: AuthenticatedAdminFinanceRoute,
  AuthenticatedAdminMediaRoute: AuthenticatedAdminMediaRoute,
  AuthenticatedAdminMembersRoute: AuthenticatedAdminMembersRouteWithChildren,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminProfileRoute: AuthenticatedAdminProfileRoute,
  AuthenticatedAdminProjectsRoute: AuthenticatedAdminProjectsRouteWithChildren,
  AuthenticatedAdminReportsRoute: AuthenticatedAdminReportsRoute,
  AuthenticatedAdminSystemRoute: AuthenticatedAdminSystemRoute,
  AuthenticatedAdminTeamLeadersRoute:
    AuthenticatedAdminTeamLeadersRouteWithChildren,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminWithdrawalsRoute: AuthenticatedAdminWithdrawalsRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminCmsBrandRoute: AuthenticatedAdminCmsBrandRoute,
  AuthenticatedAdminCmsGlobalRoute: AuthenticatedAdminCmsGlobalRoute,
  AuthenticatedAdminCmsMediaRoute: AuthenticatedAdminCmsMediaRoute,
  AuthenticatedAdminCmsPagesRoute: AuthenticatedAdminCmsPagesRouteWithChildren,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmFollowupsRoute: typeof AuthenticatedCrmFollowupsRoute
  AuthenticatedCrmNewRoute: typeof AuthenticatedCrmNewRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmFollowupsRoute: AuthenticatedCrmFollowupsRoute,
  AuthenticatedCrmNewRoute: AuthenticatedCrmNewRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedLeaderMembersRouteChildren {
  AuthenticatedLeaderMembersIdRoute: typeof AuthenticatedLeaderMembersIdRoute
}

const AuthenticatedLeaderMembersRouteChildren: AuthenticatedLeaderMembersRouteChildren =
  {
    AuthenticatedLeaderMembersIdRoute: AuthenticatedLeaderMembersIdRoute,
  }

const AuthenticatedLeaderMembersRouteWithChildren =
  AuthenticatedLeaderMembersRoute._addFileChildren(
    AuthenticatedLeaderMembersRouteChildren,
  )

interface AuthenticatedLeaderRouteChildren {
  AuthenticatedLeaderAnalyticsRoute: typeof AuthenticatedLeaderAnalyticsRoute
  AuthenticatedLeaderLeaderboardRoute: typeof AuthenticatedLeaderLeaderboardRoute
  AuthenticatedLeaderMembersRoute: typeof AuthenticatedLeaderMembersRouteWithChildren
  AuthenticatedLeaderNotificationsRoute: typeof AuthenticatedLeaderNotificationsRoute
  AuthenticatedLeaderProfileRoute: typeof AuthenticatedLeaderProfileRoute
  AuthenticatedLeaderProjectsRoute: typeof AuthenticatedLeaderProjectsRoute
  AuthenticatedLeaderSettingsRoute: typeof AuthenticatedLeaderSettingsRoute
  AuthenticatedLeaderWithdrawalsRoute: typeof AuthenticatedLeaderWithdrawalsRoute
  AuthenticatedLeaderIndexRoute: typeof AuthenticatedLeaderIndexRoute
}

const AuthenticatedLeaderRouteChildren: AuthenticatedLeaderRouteChildren = {
  AuthenticatedLeaderAnalyticsRoute: AuthenticatedLeaderAnalyticsRoute,
  AuthenticatedLeaderLeaderboardRoute: AuthenticatedLeaderLeaderboardRoute,
  AuthenticatedLeaderMembersRoute: AuthenticatedLeaderMembersRouteWithChildren,
  AuthenticatedLeaderNotificationsRoute: AuthenticatedLeaderNotificationsRoute,
  AuthenticatedLeaderProfileRoute: AuthenticatedLeaderProfileRoute,
  AuthenticatedLeaderProjectsRoute: AuthenticatedLeaderProjectsRoute,
  AuthenticatedLeaderSettingsRoute: AuthenticatedLeaderSettingsRoute,
  AuthenticatedLeaderWithdrawalsRoute: AuthenticatedLeaderWithdrawalsRoute,
  AuthenticatedLeaderIndexRoute: AuthenticatedLeaderIndexRoute,
}

const AuthenticatedLeaderRouteWithChildren =
  AuthenticatedLeaderRoute._addFileChildren(AuthenticatedLeaderRouteChildren)

interface AuthenticatedMemberSalesRouteChildren {
  AuthenticatedMemberSalesIdRoute: typeof AuthenticatedMemberSalesIdRoute
}

const AuthenticatedMemberSalesRouteChildren: AuthenticatedMemberSalesRouteChildren =
  {
    AuthenticatedMemberSalesIdRoute: AuthenticatedMemberSalesIdRoute,
  }

const AuthenticatedMemberSalesRouteWithChildren =
  AuthenticatedMemberSalesRoute._addFileChildren(
    AuthenticatedMemberSalesRouteChildren,
  )

interface AuthenticatedMemberRouteChildren {
  AuthenticatedMemberAnalyticsRoute: typeof AuthenticatedMemberAnalyticsRoute
  AuthenticatedMemberCommissionRoute: typeof AuthenticatedMemberCommissionRoute
  AuthenticatedMemberLeaderboardRoute: typeof AuthenticatedMemberLeaderboardRoute
  AuthenticatedMemberNotificationsRoute: typeof AuthenticatedMemberNotificationsRoute
  AuthenticatedMemberProfileRoute: typeof AuthenticatedMemberProfileRoute
  AuthenticatedMemberReferralsRoute: typeof AuthenticatedMemberReferralsRoute
  AuthenticatedMemberSalesRoute: typeof AuthenticatedMemberSalesRouteWithChildren
  AuthenticatedMemberSettingsRoute: typeof AuthenticatedMemberSettingsRoute
  AuthenticatedMemberTipsRoute: typeof AuthenticatedMemberTipsRoute
  AuthenticatedMemberWalletRoute: typeof AuthenticatedMemberWalletRoute
  AuthenticatedMemberWithdrawalsRoute: typeof AuthenticatedMemberWithdrawalsRoute
  AuthenticatedMemberIndexRoute: typeof AuthenticatedMemberIndexRoute
}

const AuthenticatedMemberRouteChildren: AuthenticatedMemberRouteChildren = {
  AuthenticatedMemberAnalyticsRoute: AuthenticatedMemberAnalyticsRoute,
  AuthenticatedMemberCommissionRoute: AuthenticatedMemberCommissionRoute,
  AuthenticatedMemberLeaderboardRoute: AuthenticatedMemberLeaderboardRoute,
  AuthenticatedMemberNotificationsRoute: AuthenticatedMemberNotificationsRoute,
  AuthenticatedMemberProfileRoute: AuthenticatedMemberProfileRoute,
  AuthenticatedMemberReferralsRoute: AuthenticatedMemberReferralsRoute,
  AuthenticatedMemberSalesRoute: AuthenticatedMemberSalesRouteWithChildren,
  AuthenticatedMemberSettingsRoute: AuthenticatedMemberSettingsRoute,
  AuthenticatedMemberTipsRoute: AuthenticatedMemberTipsRoute,
  AuthenticatedMemberWalletRoute: AuthenticatedMemberWalletRoute,
  AuthenticatedMemberWithdrawalsRoute: AuthenticatedMemberWithdrawalsRoute,
  AuthenticatedMemberIndexRoute: AuthenticatedMemberIndexRoute,
}

const AuthenticatedMemberRouteWithChildren =
  AuthenticatedMemberRoute._addFileChildren(AuthenticatedMemberRouteChildren)

interface AuthenticatedSalesWorkflowRouteChildren {
  AuthenticatedSalesWorkflowIdRoute: typeof AuthenticatedSalesWorkflowIdRoute
  AuthenticatedSalesWorkflowNewRoute: typeof AuthenticatedSalesWorkflowNewRoute
}

const AuthenticatedSalesWorkflowRouteChildren: AuthenticatedSalesWorkflowRouteChildren =
  {
    AuthenticatedSalesWorkflowIdRoute: AuthenticatedSalesWorkflowIdRoute,
    AuthenticatedSalesWorkflowNewRoute: AuthenticatedSalesWorkflowNewRoute,
  }

const AuthenticatedSalesWorkflowRouteWithChildren =
  AuthenticatedSalesWorkflowRoute._addFileChildren(
    AuthenticatedSalesWorkflowRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeaderRoute: typeof AuthenticatedLeaderRouteWithChildren
  AuthenticatedMemberRoute: typeof AuthenticatedMemberRouteWithChildren
  AuthenticatedSalesWorkflowRoute: typeof AuthenticatedSalesWorkflowRouteWithChildren
  AuthenticatedCommissionsIdRoute: typeof AuthenticatedCommissionsIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeaderRoute: AuthenticatedLeaderRouteWithChildren,
  AuthenticatedMemberRoute: AuthenticatedMemberRouteWithChildren,
  AuthenticatedSalesWorkflowRoute: AuthenticatedSalesWorkflowRouteWithChildren,
  AuthenticatedCommissionsIdRoute: AuthenticatedCommissionsIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ProjectsRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AuthRoute: AuthRoute,
  ProjectsRoute: ProjectsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  ErrorKindRoute: ErrorKindRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicHooksSystemMaintenanceRoute: ApiPublicHooksSystemMaintenanceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
